### ISSUE TITLE
eclipse update site not working

### ISSUE THREAD

**Issue by buzz3791** [briandealwis/ferret#42]
The eclipse update sites referenced in

https://github.com/briandealwis/ferret/blob/master/README.md

are not working.  I tried both

http://manumitting.com/tools/eclipse/ferret/STABLE
http://manumitting.com/tools/eclipse/ferret/LATEST

and neither seems to result in an Eclipse update site.

**Comment by briandealwis** [comment]
Indeed `STABLE` was meant to be `stable`, but I've put a link there now so either will work.
`LATEST` works for me though.  Could you retry?

**Comment by briandealwis** [comment]
Closing as both work for me.  Please re-open if required.
