### ISSUE TITLE
Java editor tab problem decoration is not updated anymore

### ISSUE THREAD

**Issue by iloveeclipse** [briandealwis/ferret#82]
Open any java file in the editor.
Introduce compile error and save.
Notice that the error is shown in ruler but not on the editor tab.
Close editor and open it again.
Error overlay is shown on the editor tab now.
Fix compile error and save.
Notice that the error is removed from ruler but not from the editor tab.

The root cause is that there is no adapter wired anymore from FileEditorInput to IJavaElement!

Because of this JavaEditorErrorTickUpdater.problemsChanged(IResource[], boolean) can't find IJavaElement for given IEditorInput and so does not call to JavaEditorErrorTickUpdater.updateEditorImage(IJavaElement).

I see in the debugger that some ferret factory claims to provide an adapter for FileEditorInput but returns null. After uninstalling Ferret I see that the editor tabs are updated again.

This is pretty severe and is a blocker for me to use Ferret.

**Comment by briandealwis** [comment]
The fix will be available in the latest repo at http://manumitting.com/tools/eclipse/ferret/LATEST and I'll promote it in a day or so.

**Comment by briandealwis** [comment]
(And thank you @iloveeclipse for tracking down the issue.)
