### ISSUE TITLE
Disable debugging output

### ISSUE THREAD

**Issue by theres-waldo** [briandealwis/ferret#9]
Since installing this plugin, the following output started appearing in the terminal from which I start Eclipse:

    JavaModelHelper: reset(): cancelling futures...

I don't think this should be shown by default, it's a distraction.

**Comment by briandealwis** [comment]
Agreed.  Fixed in `master`.

**Comment by theres-waldo** [comment]
Has a new version of the plugin that includes this fix been released?

**Comment by briandealwis** [comment]
Yes: it was fixed in commit 9fb7d3dd3828ac25e3cdc7c8089ff9e6bb2108cb and was released in v0.5.0.  The latest release is always available from the p2 update site at:

   http://manumitting.com/tools/eclipse/ferret/stable

**Comment by theres-waldo** [comment]
> Yes: it was fixed in commit 9fb7d3d and was released in v0.5.0. The latest release is always available from the p2 update site at:
>
> http://manumitting.com/tools/eclipse/ferret/stable

Thanks. I was using http://manumitting.com/tools/eclipse/ferret, and v0.5.0 was not available there.

FWIW, the instructions at http://manumitting.com/tools/eclipse/ferret/stable say "To install, use the following update site: http://manumitting.com/tools/eclipse/ferret/", so you might want to update that.

**Comment by briandealwis** [comment]
http://manumitting.com/tools/eclipse/ferret is a composite repo that points to `/stable`, so that should still work too.
